import { readFileSync } from "node:fs";

import { browser } from "@wdio/globals";

// `./browser-tauri.d.ts` is ambient (type-only) — picked up via
// `tsconfig.wdio.json`'s `include`, not a runtime import.

/**
 * Generated by `tools/git-fixtures/src/bin/dump-mocks.rs` (design.md §4.1),
 * keyed by Tauri command name, never hand-authored, diff-checked in CI. Only
 * the fields this harness actually reads are typed here — the same
 * "mirrored, not imported" convention `e2e/support/fixture.ts` and
 * `graph-viewport.spec.ts` use, so the harness never depends on the product
 * types it exists to catch defects in.
 */
export interface HistoryMocks {
  startup_path: string;
  open_repository: {
    path: string;
    name: string;
    head: { name: string; oid: string | null; detached: boolean } | null;
    isEmpty: boolean;
    remotes: string[];
  };
  commit_graph: { rows: unknown[]; laneCount: number; truncated: boolean };
  list_refs: Array<{ name: string; kind: "localBranch" | "remoteBranch" | "tag" }>;
  working_status: { staged: unknown[]; unstaged: unknown[]; conflicted: string[] };
  /** Keyed by commit OID — see `dump-mocks.rs`. */
  commit_detail: Record<string, unknown>;
  close_repository: null;
}

const FIXTURE_PATH_TOKEN = "{{FIXTURE_PATH}}";

/**
 * Browser mode never touches a real filesystem (design.md §4.2) — this only
 * has to look like an absolute path; nothing on the mocked side reads disk.
 */
const BROWSER_FIXTURE_PATH = "/mock/e2e-fixtures/history";

function substituteToken<T>(value: T): T {
  const json = JSON.stringify(value).split(FIXTURE_PATH_TOKEN).join(BROWSER_FIXTURE_PATH);
  return JSON.parse(json) as T;
}

/** Load and token-substitute the generated mocks for a named fixture. */
export function readMocks(name = "history"): HistoryMocks {
  let raw: string;
  try {
    raw = readFileSync(`./e2e/mocks/${name}.json`, "utf-8");
  } catch (cause) {
    throw new Error(
      `Generated mocks not found at ./e2e/mocks/${name}.json. Run ` +
        `"cargo run -p git-fixtures --bin dump-mocks -- --repo target/e2e-fixtures/${name} ` +
        `--out e2e/mocks/${name}.json" first (after building the fixture).`,
      { cause },
    );
  }
  return substituteToken(JSON.parse(raw) as HistoryMocks);
}

/**
 * Register every generated payload as a `browser.tauri.mock()`, keyed by the
 * same Tauri command name the frontend passes to `invoke()` (`api.ts`).
 *
 * Must run *after* the session's initial page load, from inside a test — see
 * `welcome.spec.ts`'s timing note. `commit_detail` resolves to the first
 * commit's detail regardless of the requested id: this harness only ever
 * drives the app to its initial selection, and a constant `mockResolvedValue`
 * (data, not code) sidesteps needing a per-id `mockImplementation` closure,
 * which `@wdio/tauri-service` serialises into the browser page and therefore
 * cannot close over this function's `mocks` argument.
 */
export async function installMocks(mocks: HistoryMocks): Promise<void> {
  const constantMocks: Array<[string, unknown]> = [
    ["startup_path", mocks.startup_path],
    ["open_repository", mocks.open_repository],
    ["commit_graph", mocks.commit_graph],
    ["list_refs", mocks.list_refs],
    ["working_status", mocks.working_status],
    ["close_repository", mocks.close_repository],
    ["commit_detail", Object.values(mocks.commit_detail)[0] ?? null],
  ];

  for (const [command, value] of constantMocks) {
    const mock = await browser.tauri.mock(command);
    await mock.mockResolvedValue(value);
  }
}
