import assert from "node:assert/strict";

import { $, $$, browser } from "@wdio/globals";

import { installMocks, readMocks } from "../support/mocks";

/**
 * Browser-mode iteration loop (design.md §4.2, requirement "Browser-Mode
 * Mocks Are Generated and Diff-Checked"): the real frontend, driven in
 * Chrome against the generated `history` mocks — no Tauri binary, no
 * WebKit. Fast signal only; `e2e/native/smoke.spec.ts` is the authority.
 *
 * Timing note, because it shaped this spec's structure rather than being
 * incidental: `@wdio/tauri-service` navigates to the dev server in its own
 * `before()` hook, before any test code runs and therefore before any mock
 * exists. `App.tsx`'s mount-time `startup_path` call is unavoidably
 * unmocked on that first load and fails silently — the app boots on
 * `WelcomeScreen`, exactly as it would against a real backend with no
 * remembered/argv repository. This spec installs mocks *after* that load,
 * then drives the same "Open repository" path a user takes, which is the
 * one path that fires every mocked command safely after mocks exist.
 */
describe("browser-mode welcome", () => {
  it("opens the mocked fixture through the Open-repository flow", async () => {
    const mocks = readMocks();
    await installMocks(mocks);

    // `openDialog()` (`@tauri-apps/plugin-dialog`) is not git-core-derived
    // data — it is the user's picker choice — so it is hand-mocked here
    // rather than generated by `dump-mocks.rs`.
    const dialogMock = await browser.tauri.mock("plugin:dialog|open");
    await dialogMock.mockResolvedValue(mocks.open_repository.path);

    await $('button[title^="Open repository"]').click();

    await $('[role="listbox"]').waitForExist({ timeout: 10000 });

    const headerName = await $("header span.truncate.font-semibold").getText();
    assert.equal(
      headerName,
      mocks.open_repository.name,
      `header repo name: expected "${mocks.open_repository.name}", got "${headerName}"`,
    );

    const rows = await $$('[role="option"]');
    assert.equal(
      rows.length,
      mocks.commit_graph.rows.length,
      `expected ${mocks.commit_graph.rows.length} commit rows, got ${rows.length}`,
    );

    // "Branches" is the one sidebar section open by default (Sidebar.tsx),
    // same selector `smoke.spec.ts` (native mode) uses for the same assertion.
    const branchLabels = await $$(
      "nav section:first-of-type button span.flex-1.truncate",
    ).map((element) => element.getText());
    const expectedBranches = mocks.list_refs
      .filter((ref) => ref.kind === "localBranch")
      .map((ref) => ref.name);
    for (const branch of expectedBranches) {
      assert.ok(
        branchLabels.includes(branch),
        `sidebar branches: expected "${branch}" among ${JSON.stringify(branchLabels)}`,
      );
    }
  });
});
